---
title: What Share of Students Don't Show up In Learning Outcomes Surveys in India
author: ''
date: '2021-09-17'
slug: []
categories: []
tags: 
  - Education
lastmod: '2021-09-17T16:35:35+07:00'
keywords: []
description: ''
comment: no
toc: no
autoCollapseToc: no
postMetaInFooter: no
hiddenFromHomePage: no
contentCopyright: no
reward: no
mathjax: no
mathjaxEnableSingleDollar: no
mathjaxEnableAutoNumber: no
hideHeaderAndFooter: no
flowchartDiagrams:
  enable: no
  options: ''
sequenceDiagrams:
  enable: no
  options: ''
---

Learning outcomes surveys typically use a school-based sampling strategy -- i.e. they randomly select schools and then conduct assessments of all or some portion of students at each selected school. The advantage of school-based surveys is that they are far cheaper to conduct than household surveys. The disadvantage of school-based survey is that they potentially exclude students who aren't enrolled, don't show up on the day of the exam, or attend "unrecognised" private schools (i.e. private schools which don't have official recognition and thus are not in UDISE, the official government list of schools),

I took a stab at estimating the total share of primary school-age children excluded from school-based sampling surveys. I used data on enrollment for rural 7-10 year olds from ASER, data on enrollment of primary and upper primary children at an unrecognised school from NSSO's 71st round, and data on attendance of enrolled 7-10 year olds from NFHS 2015-16. The NFHS question asks whether the child *ever* attended school in the 2015-16 so these figures estimate the share of children that almost certainly wouldn't be included in a school-based survey. In addition, a child may be excluded because they don't show up on the day of the exam. Kremer and Muralidharan, in a national survey of rural schools conducted in 2004, found that student attendance was 75% in private schools and 64% in government schools. 

The table below gives these figures for the large states in India (excluding Telangana) and for the entire country. Overall, the share of students who would completely excluded from a school-based survey is relatively low at 10%. This surprised me somewhat. In fact, my original motivation for gathering these stats was that I thought they would show that a school-based survey would exclude far more children and thus a household survey would be a better bet. Previous estimates of the share of students attending unrecognised schools have varied between around 46% and 80%. (See footnote 6 in this [paper](https://www.tandfonline.com/doi/abs/10.1080/00220388.2020.1715943) by Kingdon for a review.) And estimates of the share of enrolled students attending school from previous versions of the NFHS were much lower. While the overall share of excluded students is relatively low, the share varies quite a bit state to state from just over 1% in HP and Sikkim to nearly 20% in Bihar. 

The upshot for me is that school-based surveys can do a decent job generating representative estimates of school-age children but, for states like Bihar and UP, it will be important to generate estimates of learning levels for children left out of the sampling frame. And, of course, it is also important to make sure that children actually show up on the day of the assessment. 



```{r, echo = FALSE, message=FALSE, warning=FALSE}
library(tidyverse); library(forcats)
excluded <- structure(list(State = c("AP", "AR", "AS", "BR", "CG", "GJ", 
"HR", "HP", "JK", "JH", "KA", "KL", "MP", "MH", "MN", "ML", "MZ", 
"NL", "OR", "PB", "RJ", "SK", "TN", "TR", "UK", "UP", "WB", "India"
), Unenrolled = c(0.004, 0.031, 0.009, 0.031, 0.017, 0.006, 0.012, 
0.002, 0.006, 0.015, 0.002, 0, 0.022, 0.003, 0.009, 0.045, 0.003, 
0.015, 0.008, 0.005, 0.02, 0.005, 0, 0.003, 0.008, 0.028, 0.001, 
0.016), Unrecognised = c(0.012, 0.005, 0.007, 0.068, 0.016, 0.005, 
0.018, 0.004, 0.005, 0.059, 0.007, 0.032, 0.007, 0.013, 0.007, 
0.063, 0.038, 0, 0.009, 0.039, 0.016, 0, 0.012, 0.007, 0.047, 
0.088, 0.015, 0.035), Never_attended = c(0.011, 0.061, 0.038, 
0.094, 0.033, 0.038, 0.033, 0.006, 0.023, 0.059, 0.021, 0.002, 
0.06, 0.023, 0.014, 0.035, 0.029, 0.036, 0.038, 0.019, 0.066, 
0.007, 0.009, 0.009, 0.081, 0.031, 0.024, 0.05)), class = "data.frame", row.names = c(NA, 
-28L))

# Get rid of the all india row and convert to percentage
excluded <- excluded %>% 
  filter(State != "India") %>% 
  mutate(across(c(Unenrolled, Unrecognised, Never_attended), ~ .x *100))

# Get the factor levels into the approrpriate order
excluded <- excluded %>% 
  mutate(State = fct_reorder(excluded$State, -(excluded$Never_attended + excluded$Unrecognised + excluded$Unenrolled)))

excluded_long <- excluded %>% 
  pivot_longer(!State, names_to = "Category", values_to = "Share")

ggplot(excluded_long, aes(State, fill = Category, y = Share)) +
  geom_col(position = position_stack(reverse = TRUE)) +
  labs(x = "", y = "% children 7-10", title = "Children excluded from School-based Survey Sampling Frame", fill = "Reason for exclusion") +
  theme(axis.text.x = element_text(angle = 90))
  
```







